Adds remirror functionality
HippieStation/PRMirror pull request #16
Opened 2019-12-26 10:08 UTC by MCterra10

I literally learnt go just to fix this shit.

2019-12-26 10:11 UTC, MCterra10 commented
worth noting that I moved labeling the PR to a webhook and added a force push to the script to remirror properly

2020-03-05 08:17 UTC, MCterra10 commented
hurry up you dumbass :b:ippie maintainers

2020-03-05 15:46 UTC, jamie-34254 commented
I don't do anything for Hippie anymore or play SS13 but I've asked them to add me back to the repo so I can review and merge this

2020-03-05 22:34 UTC, j-mie requested changes

2020-03-05 22:34 UTC, j-mie commented on prmirror.go
> +		p.Database.AddEvent(event.GetID())
I'm not sure if these IDs are the same kind of ID for both PullRequestEvents and CommentEvents are they? If they're the same ID then this is fine but if not you're going to need to prepend `pr` and `comment` to the IDs to stop collisions between IDs and PRs

2020-03-05 22:34 UTC, j-mie commented on prmirror.go
> -			p.AddLabels(prID, []string{"Upstream PR Merged"})
How come you're removing this?

2020-03-05 22:34 UTC, j-mie commented on prmirror.go
> +		temp := strings.Split(body, "/")
what is this even doing. It looks like you're getting the upstream PullRequest ID from the downstream PR maybe? If so there's definitely a better way of doing that

2020-03-05 22:34 UTC, j-mie commented on prmirror.go
> +		temp := strings.Split(body, "/")
Looks like we store a map of Upstream/Downstream using `StoreMirror` - you can probably implement a way to get the Upstream PR ID from the Downstream PR ID using that

2020-03-23 10:32 UTC, MCterra10 commented
oh wow someone answered, okay I'll address the reviews when I get some time

2020-03-23 10:35 UTC, MCterra10 commented on prmirror.go
> -			p.AddLabels(prID, []string{"Upstream PR Merged"})
That's my bad, I removed it because it's handled by our webhook system. If it's an issue it can be added back.

2020-03-23 10:36 UTC, MCterra10 commented on prmirror.go
> +		temp := strings.Split(body, "/")
literally no experience in go other than what I found online in brief tutorials, so that's really beyond my scope I'm afraid

2020-03-23 10:37 UTC, MCterra10 commented on prmirror.go
> +		p.Database.AddEvent(event.GetID())
hmm, I can do that, shouldn't be too hard to alter the method

2020-04-09 09:58 UTC, MCterra10 commented on prmirror.go
> -			p.AddLabels(prID, []string{"Upstream PR Merged"})
made it into a config option

2020-04-09 09:58 UTC, MCterra10 commented on prmirror.go
> +		p.Database.AddEvent(event.GetID())
done

2020-04-09 09:58 UTC, MCterra10 commented on prmirror.go
> +		temp := strings.Split(body, "/")
I added some more error handling for this, other than that I don't really know how to improve it further, given my experience with go.

2020-05-01 04:03 UTC, closed without merging

2020-05-01 18:02 UTC, Neo1w commented
@MCterra10 why you close

2020-05-19 09:16 UTC, MCterra10 commented
@Neo1w maintainer wasn't responding

2020-05-19 09:16 UTC, MCterra10 commented
If you want the code changes, just fork from austation's PR Mirror repo.

2020-05-19 22:39 UTC, Neo1w commented
fair